Geoplateforme/plugin-qgis-geoplateforme

.github/labeler.yml
.pre-commit-config.yaml
.vscode/extensions.json
CONTRIBUTING.md
geoplateforme/api/client.py
geoplateforme/api/processing.py
geoplateforme/api/user.py
geoplateforme/gui/cbx_stored_data.py
geoplateforme/gui/dlg_settings.py
geoplateforme/gui/gui_commons.py
geoplateforme/gui/mdl_stored_data.py
geoplateforme/gui/mdl_table_relation.py
geoplateforme/gui/proxy_model_stored_data.py
geoplateforme/gui/report/dlg_report.py
geoplateforme/gui/report/wdg_upload_log.py
geoplateforme/gui/tile_creation/qwp_tile_generation_sample.py
geoplateforme/gui/tile_creation/qwp_tile_generation_status.py
geoplateforme/gui/upload_creation/mdl_upload_files.py
geoplateforme/plugin_main.py
geoplateforme/processing/check_layer.py
geoplateforme/toolbelt/check_state_model.py
requirements/development.txt
ruff.toml

see: https://docs.astral.sh/ruff/faq/#how-does-ruffs-formatter-compare-to-black
> The Ruff formatter is designed to be a drop-in replacement for [Black](https://github.com/psf/black).

update(tooling): replace black with ruff formatter

---

.vscode/settings.json

Following up https://github.com/Geoplateforme/plugin-qgis-geoplateforme/pull/3

update(tooling): set ruff as Python formatter in VS Code

---

.github/workflows/documentation.yml
.github/workflows/linter.yml
.github/workflows/package_and_release.yml
.github/workflows/tester.yml
geoplateforme/metadata.txt

This PR:
- fix the broken URL https://geoplateforme.github.io/plugin-qgis-geoplateforme/plugins.xml (see https://github.com/Geoplateforme/plugin-qgis-geoplateforme/actions/runs/14535376853/job/40782629666 for an example of failing job)
- homogenize YAML formatting
- add -DEV suffix to plugin's version to distinguish it from future published versions

CI: fix packaged plugin and repository was missing in documentation

---

geoplateforme/api/user.py

fix https://github.com/Geoplateforme/plugin-qgis-geoplateforme/issues/15
Permet de rendre le paramètre datastore optionnel pour une communauté.
@IGNF-Xavier il faudrait si possible nous ajouter à une telle communauté pour que l'on puisse tester le fix.

fix(user): fix community without user 

---

geoplateforme/toolbelt/network_manager.py

Une description additionnelle des erreurs est disponible dans le retour de l'API. 
Voici par exemple le message retourné en cas d'erreur de préfixe lors d'une publication:
```json
{
"error": "Bad Request",
"error_description": [
"Le layer_name de la configuration doit être préfixé par SANDBOX"
]
}
```
L'objectif de cette PR est de pouvoir récupérer l'erreur dans l'exception `ConnectionError` afin d'indiquer le maximum d'information aux utilisateurs.
- refactoring de la vérification des requêtes : ajout d'une méthode `check_request_result`
- refactoring de l'ajout du résultat des requêtes dans les logs : ajout d'une méthode `log_reply`

feat(network manager): get error from request reply

---

geoplateforme/gui/cbx_dataset.py
geoplateforme/gui/dashboard/wdg_dashboard.py
geoplateforme/gui/dashboard/wdg_dashboard.ui
geoplateforme/gui/upload_creation/qwp_upload_creation.py
geoplateforme/gui/upload_creation/qwp_upload_edition.py
geoplateforme/gui/upload_creation/wdg_upload_creation.py
geoplateforme/gui/upload_creation/wdg_upload_creation.ui
geoplateforme/gui/upload_creation/wzd_upload_creation.py
geoplateforme/plugin_main.py

- ajout d'un bouton pour créer un dataset
- ajout d'un bouton pour ajouter des données à un dataset
- correction de la fonction refresh du dashboard

feature(dashboard): add button to create a new dataset or add data to existing dataset

---

geoplateforme/processing/upload_database_integration.py
geoplateforme/processing/vector_db_creation.py
geoplateforme/resources/help/upload_database_integration.md

Modification processing de création de base de données vectorielle pour ne plus prendre en paramètre un fichier .json mais des paramètres de processing.
Ajout d'une documentation.

4- feat(upload to vector): refactor to replace .json by processing parameter

---

docs/usage/processings.md
geoplateforme/processing/upload_from_layers.py
geoplateforme/resources/help/upload_from_layers.md

Ajout d'une option pour ajouter des fichiers complémentaires lors d'une livraison depuis des couches vectorielles.

5- feat(upload from layer): add additionnal files option

---

docs/usage/processings.md
geoplateforme/gui/tile_creation/qwp_tile_generation_status.py
geoplateforme/processing/tile_creation.py
geoplateforme/resources/help/tile_creation.md

Mise à jour du processing de génération de tuiles vectorielles pour ne plus utiliser de fichier .json intermédiaire.
🎫 JIRA :
- https://jira.worldline-solutions.com/browse/IGNGPF-4791

feat(tile generation): refactor to remove JSON file use

---

docs/usage/processings.md
geoplateforme/gui/publication_creation/qwp_status.py
geoplateforme/processing/upload_publication.py
geoplateforme/resources/help/vector_tile_publish.md

Mise à jour du processing de publication de tuiles vectorielles pour ne plus utiliser de fichier .json intermédiaire.
🎫 JIRA :
- https://jira.worldline-solutions.com/browse/IGNGPF-4865

feat(tile publish): refactor to remove JSON file use

---

geoplateforme/api/custom_exceptions.py
geoplateforme/api/metadata.py
geoplateforme/gui/dashboard/wdg_dashboard.py

- add metadata class to fit API entrepot metadata
- convert API metadata to QGIS metadata by parsing xml
- fill metadata QGIS Widget

add metadata class and fill by parsing xml

---

geoplateforme/gui/cbx_dataset.py

La combobox des jeux de données est maintenant triée par nom:
Ajout d'un `QSortProxyModel` dans la combobox.

feat(dataset): sort by name in combobox

---

geoplateforme/api/upload.py
geoplateforme/gui/dashboard/wdg_dashboard.py
geoplateforme/gui/dashboard/wdg_upload_details.py
geoplateforme/gui/dashboard/wdg_upload_details.ui

Lorsqu'une livraison est sélectionnée, un widget avec les détails de la livraison est affiché:
🎫 JIRA :
- https://jira.worldline-solutions.com/browse/IGNGPF-4830

feat(upload): add widget to display upload details

---

geoplateforme/api/processing.py
geoplateforme/processing/tile_creation.py
geoplateforme/processing/upload_database_integration.py
geoplateforme/toolbelt/preferences.py

- Ajout de paramètre non accessible pour l'utlisateur pour la définition des noms de processing pour la récupération dans l'entrepot.

feat(processing): add available processings name in settings (not visible to user)

---

geoplateforme/gui/upload_creation/wzd_upload_creation.py

Vérification du lancement du processing d'intégration en base de données avant fermeture du QWizard de création de dataset.

feat(upload): check if db integration has started before wizard close

---

geoplateforme/gui/dlg_authentication.py
geoplateforme/gui/dlg_authentication.ui
geoplateforme/gui/user/dlg_user.py
geoplateforme/plugin_main.py

Affiche les informations de l'utilisateur si l'utilisateur est connecté

feat(auth): add user dialog if log in

---

geoplateforme/gui/upload_creation/qwp_upload_creation.py

fix : https://github.com/Geoplateforme/plugin-qgis-geoplateforme/issues/70

fix(upload): set datasetname in tags

---

geoplateforme/gui/dashboard/wdg_dashboard.py
geoplateforme/gui/dashboard/wdg_upload_details.py
geoplateforme/gui/upload_database_integration/qwp_upload_database_integration.py
geoplateforme/gui/upload_database_integration/qwp_upload_database_integration.ui
geoplateforme/gui/upload_database_integration/qwp_vector_db_edition.py
geoplateforme/gui/upload_database_integration/qwp_vector_db_edition.ui
geoplateforme/gui/upload_database_integration/wzd_upload_database_integration.py

Ajout d'une action lors de la sélection des uploads pour pouvoir générer une base de données vectorielle.
La base de données est sélection après le lancement de la génération.

feat(vector db): add generation wizard

---

geoplateforme/gui/dlg_settings.py
geoplateforme/plugin_main.py

- Déplacement des actions du plugin dans le menu Plugins de QGIS.
- Ajout d'une action pour rapporter une issue
- Correction url pour issue (mauvais template)
- Ajout de @IGNF-Xavier  comme assignee par défaut.

feat(ui): move to plugin menu and add report button

---

geoplateforme/api/custom_exceptions.py
geoplateforme/api/offerings.py
geoplateforme/gui/dashboard/wdg_dashboard.py
geoplateforme/gui/mdl_offering.py

Affichage de la liste des offerings plutôt que la liste des configurations.

feat(service): display offering instead of configuration

---

geoplateforme/gui/dashboard/wdg_dashboard.py
geoplateforme/gui/dashboard/wdg_dashboard.ui
geoplateforme/gui/dashboard/wdg_service_details.py
geoplateforme/gui/dashboard/wdg_service_details.ui

Affichage d'un panneau pour le détail des services.
Pour l'instant seul l'ID et le nom sont affichés.
Les actions complémentaires seront ajoutées dans une autre PR.

feat(service): add details zone

---

geoplateforme/api/configuration.py
geoplateforme/api/offerings.py
geoplateforme/gui/dashboard/dlg_stored_data_details.py
geoplateforme/gui/dashboard/wdg_dashboard.py
geoplateforme/gui/dashboard/wdg_dashboard.ui
geoplateforme/gui/mdl_offering.py
geoplateforme/gui/publication_creation/qwp_status.py
geoplateforme/gui/publication_creation/qwp_status.ui
geoplateforme/gui/publication_creation/wzd_publication_creation.py
geoplateforme/gui/update_publication/wzd_update_publication.py
geoplateforme/gui/wfs_publication/qwp_wfs_publication_status.py
geoplateforme/gui/wfs_publication/qwp_wfs_publication_status.ui
geoplateforme/gui/wfs_publication/wzd_publication_creation.py
geoplateforme/gui/wms_vector_publication/qwp_wms_vector_publication_status.py
geoplateforme/gui/wms_vector_publication/qwp_wms_vector_publication_status.ui
geoplateforme/gui/wms_vector_publication/wzd_publication_creation.py
geoplateforme/processing/upload_publication.py
geoplateforme/processing/wfs_publication.py
geoplateforme/processing/wms_publication.py
geoplateforme/resources/help/vector_tile_publish.md

- return offering id in processings for publication
- add selection of service in dashboard
- update all publication wizard to store offering id

feat(publication): select offering after publication

---

geoplateforme/api/configuration.py
geoplateforme/api/datastore.py
geoplateforme/gui/create_raster_tiles_from_wms_vector/qwp_tile_generation_edition.py
geoplateforme/gui/create_raster_tiles_from_wms_vector/qwp_tile_generation_edition.ui
geoplateforme/gui/create_raster_tiles_from_wms_vector/qwp_tile_generation_status.py
geoplateforme/gui/create_raster_tiles_from_wms_vector/qwp_tile_generation_status.ui
geoplateforme/gui/create_raster_tiles_from_wms_vector/wzd_raster_tiles_from_wms_vector.py
geoplateforme/gui/dashboard/wdg_dashboard.py
geoplateforme/gui/dashboard/wdg_service_details.py
geoplateforme/gui/tile_creation/qwp_tile_generation_edition.py

Création d'une pyramide raster depuis un service WMS-VECTOR.
Pour l'instant on utilise des valeurs par défaut, comme pour cartes.gouv.fr.
Seul les niveaux de zoom peuvent être définis.
🎫 JIRA :
- https://jira.worldline-solutions.com/browse/IGNGPF-4788

feat(raster tiles): add wizard for raster tiles creation from WMS-VECTOR service

---

docs/usage/processings.md
geoplateforme/processing/provider.py
geoplateforme/processing/wmts_publication.py
geoplateforme/resources/help/wmts_publish.md

Initialisation processing pour publication WMTS
🎫 JIRA :
- https://jira.worldline-solutions.com/browse/IGNGPF-4796

feat(wmts): init processing for publication

---

geoplateforme/gui/dashboard/dlg_stored_data_details.py
geoplateforme/gui/wmts_publication/qwp_publication_form.py
geoplateforme/gui/wmts_publication/qwp_publication_form.ui
geoplateforme/gui/wmts_publication/qwp_wmts_edition.py
geoplateforme/gui/wmts_publication/qwp_wmts_edition.ui
geoplateforme/gui/wmts_publication/qwp_wmts_publication_status.py
geoplateforme/gui/wmts_publication/qwp_wmts_publication_status.ui
geoplateforme/gui/wmts_publication/wzd_publication_creation.py

Initialisation wizard pour publication WMTS-TMS
🎫 JIRA :
- https://jira.worldline-solutions.com/browse/IGNGPF-4787

feat(wmts): add wizard for publication

---

geoplateforme/gui/dashboard/dlg_stored_data_details.py
geoplateforme/gui/dashboard/wdg_dashboard.py

Ajout d'un bouton pour la suppression d'une donnée stockée.
Un refresh du dataset est effectué après la suppression.

feat(delete): add delete action for stored data

---

geoplateforme/api/custom_exceptions.py
geoplateforme/api/user_key.py
geoplateforme/gui/user_keys/dlg_user_keys.py
geoplateforme/gui/user_keys/dlg_user_keys.ui
geoplateforme/gui/user_keys/mdl_user_keys.py
geoplateforme/gui/user_keys/wdg_user_keys.py
geoplateforme/gui/user_keys/wdg_user_keys.ui
geoplateforme/plugin_main.py

- ajout d'un manager pour récupérer la liste des clés disponibles : `UserKeyRequestManager`
- ajout d'un model pour affichage d'une liste de clés dans une table : `UserKeysListModel`
- affichage de la liste des clés disponibles dans une table 
- prévision widget pour l'affichage d'informations complémentaires au clic comme cela est effectué pour les livraisons / données stockées / services

feat(user key): display available keys in table

---

geoplateforme/api/user.py
geoplateforme/gui/mdl_community.py
geoplateforme/gui/mdl_offering.py
geoplateforme/gui/permissions/dlg_permission_creation.py
geoplateforme/gui/permissions/dlg_permission_creation.ui
geoplateforme/gui/permissions/wdg_permission_creation.py
geoplateforme/gui/permissions/wdg_permission_creation.ui
geoplateforme/gui/permissions/wdg_permissions.py
geoplateforme/gui/permissions/wdg_permissions.ui
geoplateforme/gui/proxy_model_offering.py

- ajout d'un modèle pour afficher les communautés d'un utilisateur (avec option d'affichage de checkbox)
- modification modèle pour offerring pour ajout d'option d'affichage de checkbox
- ajout d'un modèle proxy pour offerring pour ne voir que les offres fermées
- ajout d'un widget pour la définition des paramètres nécessaires pour la création de permissions
- ajout d'une dialog pour récupérer les paramètres et lancer le processing de création de permissions
🎫 JIRA :
- https://jira.worldline-solutions.com/browse/IGNGPF-4866

feat(permission): add permission creation

---

docs/usage/processings.md
geoplateforme/api/custom_exceptions.py
geoplateforme/api/user_key.py
geoplateforme/processing/provider.py
geoplateforme/processing/user_key/create_accesses.py
geoplateforme/resources/help/create_accesses.md
tests/qgis/processings/user_key/test_accesses_creation.py

- ajout d'un processing pour la création d'accès sur une clé
🎫 JIRA :
- https://jira.worldline-solutions.com/browse/IGNGPF-4882

feat(user key): add accesses creation processing

---

geoplateforme/api/custom_exceptions.py
geoplateforme/api/user_permission.py
geoplateforme/gui/user_keys/dlg_user_key_creation.py
geoplateforme/gui/user_keys/dlg_user_key_creation.ui
geoplateforme/gui/user_keys/mdl_user_permissions.py
geoplateforme/gui/user_keys/wdg_user_key_creation.py
geoplateforme/gui/user_keys/wdg_user_key_creation.ui
geoplateforme/gui/user_keys/wdg_user_key_ip_filter.py
geoplateforme/gui/user_keys/wdg_user_key_ip_filter.ui
geoplateforme/gui/user_keys/wdg_user_keys.py
geoplateforme/gui/user_keys/wdg_user_keys.ui

- ajout d'un manager pour récupérer les permissions disponibles pour un utilisateur `UserPermissionRequestManager`
- ajout d'un widget pour créer une clé utilisateur (type, filtrage IP) et les permissions associées
- ajout dialog pour :
- création clé avec processing associé
- création access avec processing associé
🎫 JIRA :
- https://jira.worldline-solutions.com/browse/IGNGPF-4882

feat(user key): add dialog to create user key

---

geoplateforme/api/custom_exceptions.py
geoplateforme/api/key_access.py
geoplateforme/api/permissions.py
geoplateforme/gui/user_keys/mdl_user_keys.py
geoplateforme/gui/user_keys/mdl_user_permissions.py
geoplateforme/gui/user_keys/wdg_user_key.py
geoplateforme/gui/user_keys/wdg_user_key.ui
geoplateforme/gui/user_keys/wdg_user_keys.py

- ajout d'un widget pour la visualisation d'une clé utilisateur
- ajout d'un manager pour récupérer les accès pour une clé
Prévu dans des prochaines PR:
- ajout bouton pour suppression clé
- ajout bouton pour édition / sauvegarde clé
🎫 JIRA :
- https://jira.worldline-solutions.com/browse/IGNGPF-4882

feat(user key): display user key

---

geoplateforme/gui/user_keys/wdg_ip_filter_table.py
geoplateforme/gui/user_keys/wdg_ip_filter_table.ui
geoplateforme/toolbelt/lne_ip_cidr_adress.py

Ajout d'une vérification de l'IP CIDR avant l'ajout dans le tableau des adresses
- Utilisation d'une regexp pour vérifier le champ
- mise à jour style pour indiquer l'erreur
- ajout tooltip en cas d'erreur

feat(user key): add specific component for IP CIDR adress edit

---

docs/usage/processings.md
geoplateforme/api/custom_exceptions.py
geoplateforme/api/user_key.py
geoplateforme/gui/user_keys/mdl_user_permissions.py
geoplateforme/gui/user_keys/wdg_ip_filter_table.py
geoplateforme/gui/user_keys/wdg_user_key.py
geoplateforme/gui/user_keys/wdg_user_key.ui
geoplateforme/gui/user_keys/wdg_user_key_ip_filter.py
geoplateforme/gui/user_keys/wdg_user_keys.py
geoplateforme/processing/provider.py
geoplateforme/processing/tools/delete_offering.py
geoplateforme/processing/user_key/update_key.py
geoplateforme/resources/help/update_key.md
geoplateforme/toolbelt/network_manager.py
tests/qgis/processings/user_key/test_key_update.py

- ajout d'une méthode PATCH dans le network manager
- on ne peut pas utiliser QgsBlockingNetworkRequest car la méthode PATCH n'est pas implémentée
- on doit utiliser un manager plus haut niveau pour implémenter le PATCH 
-   mise à jour IHM pour mise en place d'un mode édition

feat(user key): add processing and GUI for update 

---

docs/usage/processings.md
geoplateforme/api/custom_exceptions.py
geoplateforme/api/permissions.py
geoplateforme/gui/dashboard/wdg_service_details.ui
geoplateforme/gui/mdl_offering.py
geoplateforme/gui/permissions/mdl_permissions.py
geoplateforme/gui/permissions/wdg_permission.py
geoplateforme/gui/permissions/wdg_permission.ui
geoplateforme/gui/permissions/wdg_permission_creation.py
geoplateforme/gui/permissions/wdg_permissions.py
geoplateforme/gui/user_keys/mdl_user_permissions.py
geoplateforme/processing/permissions/delete_permission.py
geoplateforme/processing/permissions/update_permission.py
geoplateforme/processing/provider.py
geoplateforme/resources/help/delete_permission.md
geoplateforme/resources/help/update_permission.md
tests/qgis/processings/permissions/test_permission_delete.py
tests/qgis/processings/permissions/test_permission_update.py

- ajout de processings pour suppression et modification d'une permission
- ajout d'un widget pour affichage d'une permission
- ajout bouton pour suppression / modification d'une permission

feat(permission): add widget to display / delete / update permission

---

geoplateforme/processing/generation/create_raster_tiles_from_wms_vector.py
geoplateforme/processing/generation/tile_creation.py
geoplateforme/processing/generation/upload_database_integration.py
geoplateforme/processing/permissions/create_permission.py
geoplateforme/processing/publication/upload_publication.py
geoplateforme/processing/publication/wfs_publication.py
geoplateforme/processing/publication/wms_publication.py
geoplateforme/processing/publication/wms_raster_publication.py
geoplateforme/processing/publication/wmts_publication.py
geoplateforme/processing/tools/check_layer.py
geoplateforme/processing/tools/create_geoserver_style.py
geoplateforme/processing/upload/upload_from_files.py
geoplateforme/processing/upload/upload_from_layers.py
geoplateforme/processing/user_key/create_basic_key.py
geoplateforme/processing/user_key/create_hash_key.py
geoplateforme/processing/user_key/create_oauth_key.py
geoplateforme/resources/help/check_layers.md
geoplateforme/resources/help/create_permission.md
geoplateforme/resources/help/tile_creation.md
geoplateforme/resources/help/upload_database_integration.md
tests/qgis/processings/permissions/test_permission_creation.py

Ajout d'output pour tout les processings pour permettre une utilisation dans un modeler QGIS.

fix(processing): add output to be able to use processing in QGIS modeler

---

geoplateforme/gui/permissions/wdg_permission_creation.py
geoplateforme/gui/permissions/wdg_permission_creation.ui
geoplateforme/gui/user_keys/proxy_model_user_permissions.py
geoplateforme/gui/user_keys/wdg_user_key_creation.ui
geoplateforme/gui/user_keys/wdg_user_keys.py
geoplateforme/gui/user_keys/wdg_user_keys.ui
geoplateforme/toolbelt/lne_uuid.py

- correction d'une exception lorsque la date de fin d'une permission n'est pas définie
- ajout d'un bouton pour rafraichir les clés d'accès
- ajout d'un lineedit spécifique pour l'édition de UUID
- ajout d'option pour supprimer des utilisateurs et communautés lors de l'édition d'une permission

feat(permission): small fixes and add option to delete added user and community

---

docs/usage/processings.md
geoplateforme/api/configuration.py
geoplateforme/api/custom_exceptions.py
geoplateforme/processing/provider.py
geoplateforme/processing/style/add_configuration_style.py
geoplateforme/resources/help/add_configuration_style.md
tests/qgis/processings/style/test_add_configuration_style.py

Nouveau processing pour l'ajout d'un style à une configuration de service
- ajout du style dans les annexes de l'entrepot
- récupération datastore pour avoir l'url vers l'annex créée
- récupération configuration pour avoir les styles déjà présent dans `extra`
- mise à jour configuration pour ajouter le nouveau style

feat(style): new processing to add style to service configuration

---

geoplateforme/processing/style/add_configuration_style.py
geoplateforme/processing/style/delete_configuration_style.py

- check for None and use empty dict if needed

fix(style): None return for configuration.extra if no styles available

---

geoplateforme/gui/dashboard/wdg_service_details.py
geoplateforme/gui/provider/capabilities_reader.py

Ajout d'un bouton pour charger un service dans le projet QGIS actuel.
- Si cas WMS alors le SRS est fixé a 3857
- Si cas WMTS TMS, on charge le TMS

Load service from dashboard

---

geoplateforme/gui/metadata/wdg_tagbar.py
geoplateforme/gui/provider/provider_dialog.py
geoplateforme/gui/provider/provider_dialog.ui

fix https://github.com/Geoplateforme/plugin-qgis-geoplateforme/issues/183
fix https://github.com/Geoplateforme/plugin-qgis-geoplateforme/issues/182

fix(search): add tag widget for theme field and fix production year search

---

geoplateforme/processing/permissions/create_permission.py

fix(permission): invalid groupId for create_permission

---

geoplateforme/gui/user_keys/dlg_user_key_creation.py
geoplateforme/gui/user_keys/wdg_user_key_creation.py

fix(user key): login and password are mandatory for BASIC key

---

geoplateforme/gui/dashboard/dlg_stored_data_details.py

fix(stored data): need to check enum not string for status text

---

geoplateforme/gui/dashboard/dlg_stored_data_details.py

Il était impossible de demander la suppression d'une donnée UNSTABLE.

fix(stored data): allow delete if status is UNSTABLE

---

geoplateforme/gui/dashboard/wdg_dashboard.py
geoplateforme/gui/dashboard/wdg_dashboard.ui

Ajout d'un bouton pour la suppression d'un dataset :
Demande de confirmation par l'utilisateur avec indication du nombre d'éléments supprimés:

feat(dashboard): add button to delete current dataset

---

geoplateforme/gui/dashboard/wdg_service_details.py

Il n'était pas possible de dépublier des services en état UNSTABLE.

feat(offering): allow delete of UNSTABLE offerings

---

geoplateforme/gui/metadata/wdg_metadata_details.ui
geoplateforme/gui/wdg_publication_form.ui

related #241 
Affichage de la description des métadonnées en markdown et pas la description des services.

feat(metadata): edit metadata description with markdown

---

geoplateforme/gui/publication/qwp_abstract_publish_service.py
geoplateforme/gui/publication/qwp_visibility.py
geoplateforme/gui/publication_creation/qwp_status.py
geoplateforme/gui/wfs_publication/qwp_wfs_publication_status.py
geoplateforme/gui/wms_raster_publication/qwp_wms_raster_publication_status.py
geoplateforme/gui/wms_vector_publication/qwp_wms_vector_publication_status.py
geoplateforme/gui/wmts_publication/qwp_wmts_publication_status.py

related #245 
related #222 
Le bouton précédent est activé si une erreur survient lors de la publication.

feat(publish): enable back button in case of publish error

---

geoplateforme/gui/cbx_dataset.py

fix : https://github.com/Geoplateforme/plugin-qgis-geoplateforme/issues/275

fix(dashboard): Insensitive sort for dataset

---

geoplateforme/api/metadata.py
geoplateforme/gui/metadata/wdg_metadata_details.py

fix : https://github.com/Geoplateforme/plugin-qgis-geoplateforme/issues/224
fix : https://github.com/Geoplateforme/plugin-qgis-geoplateforme/issues/228

fix(metadata): fix metadata url generation and display

---

geoplateforme/api/metadata.py

fix : https://github.com/Geoplateforme/plugin-qgis-geoplateforme/issues/179

fix/(metadata): add /1.0.0 to TMS url

---

geoplateforme/api/annexes.py
geoplateforme/api/custom_exceptions.py
geoplateforme/api/metadata.py
geoplateforme/gui/dashboard/wdg_dashboard.py
geoplateforme/gui/dashboard/wdg_dashboard.ui
geoplateforme/gui/mdl_document.py
geoplateforme/gui/metadata/wdg_metadata_details.py

related to : https://github.com/Geoplateforme/plugin-qgis-geoplateforme/issues/271

feat(document): display documents in dashboard and add logic for metadata

---

geoplateforme/gui/dashboard/dlg_select_layer_and_style.py
geoplateforme/gui/dashboard/wdg_service_details.py
geoplateforme/gui/provider/provider_dialog.py

related to : https://github.com/Geoplateforme/plugin-qgis-geoplateforme/issues/327

fix(wfs): load wfs abd select available style

---

geoplateforme/plugin_main.py

related #319
En cas de déconnection le tableau de bord était toujours affiché. En cas de déconnection il est maintenant fermé.
En cas de reset des paramètres l'activation des boutons n'était pas changé. On vérifie maintenant si on a bien une connection.

feat(user): close dashboard after disconnection or settings reset

---

geoplateforme/gui/provider/capabilities_reader.py

related to : https://github.com/Geoplateforme/plugin-qgis-geoplateforme/issues/293

fix(tms): fix reading zoom level in capabilities

---

geoplateforme/gui/styles/dlg_configuration_style_creation.py
geoplateforme/gui/styles/wdg_sld_selection.py

related #273 
Affichage d'une dialogue que l'utilisateur ne peut pas fermer lors de l'ajout des styles sur la géoplateforme.

feat(style): avoid freeze for style creation by using processing dialog

---

geoplateforme/gui/provider/provider_dialog.py

related to : https://github.com/Geoplateforme/plugin-qgis-geoplateforme/issues/205

fix(provider): display subset editor only when WFS layer is valid

---

geoplateforme/gui/tile_creation/qwp_tile_generation_status.py

related to : https://github.com/Geoplateforme/plugin-qgis-geoplateforme/issues/377

fix(tile_generation): fix regression for select zoom level

---

geoplateforme/gui/dashboard/wdg_upload_details.py

related to : https://github.com/Geoplateforme/plugin-qgis-geoplateforme/issues/279

fix(dashboard): add button to delete open upload

---

geoplateforme/gui/qwp_metadata_form.py

related to : https://github.com/Geoplateforme/plugin-qgis-geoplateforme/issues/243

fix(metadata): fix regex for metadata unique id

---

geoplateforme/constants.py
geoplateforme/metadata.txt

Modification du fichier metadata.txt et constants.py pour l'intégration du plugin BD TOPO® Extractor[ issue #332](https://github.com/Geoplateforme/plugin-qgis-geoplateforme/issues/332)
Désolé pour la pull request en plus...

feat(external plugins): add BD TOPO® Extractor plugin to Geoplateforme plugin V2

---

geoplateforme/gui/mdl_table_relation.py

related to https://github.com/Geoplateforme/plugin-qgis-geoplateforme/issues/278#issuecomment-3371508080

fix(TMS): fix regex for valid table
