geoplateforme/api/stored_data.py
geoplateforme/gui/dashboard/wdg_dashboard.py
geoplateforme/gui/mdl_dataset.py
geoplateforme/gui/mdl_stored_data.py
geoplateforme/gui/proxy_model_stored_data.py
geoplateforme/gui/report/dlg_report.py
geoplateforme/gui/storage/dlg_storage_report.py
geoplateforme/processing/tile_creation.py
geoplateforme/toolbelt/network_manager.py

J'initialise cette PR pour revoir les models stored_data et upload. Le but : 
- Avoir un niveau de chargement des objets "au besoin" :
- chargé partiellement lors de l'appel de la liste des objets 
- chargé complètement lors d'un appel à l'objet en lui même
-  l'idée c'est de ne faire un appel détaillé de l'objet que lorsque l'on veut accéder à une propriété qui en a besoin.
- simplifier les modèles pour n'avoir que les colonnes nécessaires et ne pas charger le détail des objet lors du chargement du tableau.
- gérer le choix des fields lors des appels
- utiliser le network manager pour les upload et les stored_data.

refactor(stored data): optimize stored data for better load

---

geoplateforme/plugin_main.py

Actuellement, l'installation du plugin plante :
``log
Impossible de charger l'extension 'geoplateforme' provoque une erreur lors de l'appel à sa méthode initGui() 
TypeError: object of type 'NoneType' has no len()
Traceback (most recent call last):  File "C:\PROGRA~1/QGIS34~1.4/apps/qgis-ltr/./python\qgis\utils.py", line 514, in startPlugin    plugins[packageName].initGui()  File "C:\Users/xthauvin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\geoplateforme\plugin_main.py", line 197, in initGui    self._update_actions_availability()  File "C:\Users/xthauvin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\geoplateforme\plugin_main.py", line 314, in _update_actions_availability    enabled = len(plg_settings.qgis_auth_id) != 0 …

fix(init): plg_settings.qgis_auth_id can be None and so have no length

---

geoplateforme/api/processing.py
geoplateforme/api/stored_data.py
geoplateforme/api/upload.py
geoplateforme/gui/report/dlg_report.py
geoplateforme/gui/tile_creation/qwp_tile_generation_status.py
geoplateforme/gui/update_tile_upload/qwp_update_tile_upload_run.py
geoplateforme/gui/upload_creation/qwp_upload_creation.py
geoplateforme/plugin_main.py
geoplateforme/processing/tile_creation.py
geoplateforme/processing/update_tile_upload.py
geoplateforme/processing/upload_creation.py
geoplateforme/processing/upload_database_integration.py
geoplateforme/processing/upload_publication.py
geoplateforme/processing/vector_db_creation.py
geoplateforme/toolbelt/network_manager.py

- mise à jour de la méthode de recherche des processings. On cherche maintenant les processings qui commence par une valeur choisie.
- permet d'utiliser des processings défini avec `(Bac à sable)` dans le nom du processing   
-  ajout du header `Content-Type : application/json` pour les appels POST pour les ajouts de tag et la création d'upload
- mise à jour appel POST pour la création d'un upload avec l'ajout du paramètre `path`
- utilisation du nom du fichier
- correction utilisation méthode `get_stored_data` de `StoredDataRequestManager` pour utilisation de `datastore_id` et `stored_data_id`
- correction récupération status de la stored data lors des vérifications dans les wizard
- mise à jour processing `UploadDatabaseIntegrationAlgorithm` pour retourner l'identifiant de l'execution …

feature(vector db): restore vector db creation wizard

---

geoplateforme/api/configuration.py
geoplateforme/api/datastore.py
geoplateforme/gui/publication_creation/qwp_publication_form.py
geoplateforme/gui/publication_creation/qwp_publication_form.ui
geoplateforme/gui/publication_creation/qwp_status.py
geoplateforme/plugin_main.py
geoplateforme/processing/upload_publication.py

- mise à jour manager datastore et configuration pour utiliser `NetworkRequestsManager`
- ajout fonction `add_tags`  pour `ConfigurationRequestManager`
- ajout sélection dataset lors de la publication 
- les stored data ne sont plus supprimées après la publication
- ajout tri des levels pour récupération du bottom et du top
Pour l'instant les metadata ne sont pas supportées et il est indispensable d'avoir un prefix `SANDBOX` dans le nom de la publication.
🎫 JIRA :
- https://jira.worldline-solutions.com/browse/IGNGPF-4786
- https://jira.worldline-solutions.com/browse/IGNGPF-4865

feature(vector tile publish): restore publication wizard

---

docs/index.md
docs/usage/processings.md
geoplateforme/gui/update_tile_upload/qwp_update_tile_upload_run.py
geoplateforme/gui/upload_creation/qwp_upload_creation.py
geoplateforme/processing/provider.py
geoplateforme/processing/upload_creation.py
geoplateforme/processing/upload_from_files.py
geoplateforme/processing/utils.py
geoplateforme/processing/vector_db_creation.py
geoplateforme/resources/help/upload_from_files.md

- Modification du processing de création des upload pour ne pas prendre en paramètre un fichier .json mais des parametres de processing QGIS.
- Modification nom du processing pour être plus explicite
- Initialisation de la documentation pour les processings:
- utilisation d'un fichier .md pour chaque processing
- chargement du .md pour affichage dans l'aide de QGIS
- ajout du .md dans la documentation sur GitHub Pages
🎫 JIRA :
- https://jira.worldline-solutions.com/browse/IGNGPF-4862

feature(upload) : refactor upload creation

---

geoplateforme/gui/publication_creation/qwp_publication_form.py
geoplateforme/gui/tile_creation/qwp_tile_generation_edition.py
geoplateforme/gui/update_publication/qwp_update_publication_form.py
geoplateforme/gui/update_tile_upload/qwp_update_tile_upload_edition.py

Lors de la sélection d'un datastore la liste des dataset est mise à jour.
Cependant des requêtes très nombreuses pour la récupération d'information de stored data sont observées.
Ceci est du à la connection du signal de changement d'index `currentIndexChanged` qui n'est pas déconnecté lors de la modification du datastore utilisé.
Dans cet PR des déconnections puis reconnection sont effectuées avant tout changement dans les combobox de dataset.

fix(datastore selection): disable signal connection during update

---

geoplateforme/processing/tile_creation.py

Les livraisons ne sont plus supprimées après la création d'une pyramide vectorielle

feat(tile creation): no upload remove after creation

---

geoplateforme/gui/publication_creation/qwp_status.py

Les mauvais niveaux sont renseignés lors de la publication. Il y a une inversion bottom / top.

fix(tile publish): invalid levels used

---

geoplateforme/processing/provider.py
geoplateforme/processing/upload_from_files.py
geoplateforme/processing/upload_from_layers.py
geoplateforme/processing/utils.py
geoplateforme/resources/help/upload_from_layers.md

- ajout d'un nouveau processing `geoplateforme:upload_from_layer`
- utilisation de couches vectorielles pour appel processing `geoplateforme:upload_from_files`
- vérification que les CRS en entrée sont communs
- export dans un fichier GPKG temporaire si le format n'est pas supporté. Formats supportés
- Geopackage
- ShapeFile : ajout de tout les fichiers ayant le même nom que le fichier .shp
- GeoJSON
- ajout logs dans processing `geoplateforme:upload_from_files` pour indiquer les différentes étapes de la livraison
🎫 JIRA :
- https://jira.worldline-solutions.com/browse/IGNGPF-4862

1- feat(upload): add processing for creation from QGIS layer

---

geoplateforme/gui/upload_creation/mdl_upload_files.py
geoplateforme/gui/upload_creation/wdg_layer_selection.py
geoplateforme/gui/upload_creation/wdg_layer_selection.ui
geoplateforme/gui/upload_creation/wdg_upload_creation.py
geoplateforme/gui/upload_creation/wdg_upload_creation.ui
geoplateforme/processing/upload_from_layers.py

Ajout d'une nouvelle interface pour la sélection des fichiers et des couches à intégrer dans une livraison.
- modification `UploadFilesTreeModel` pour prendre en compte des fichiers ou des couches
- ajout d'un nouveau composant `LayerSelectionStackPanel` pour la sélection des couches et des fichiers
- utilisation du widget QGIS de sélection des couches `QgsProcessingMultipleInputPanelWidget` ou `QgsProcessingMultipleInputPaneDialog`
- création composant `LayerSelectionWidget` pour sélection
Example utilisation:
[Screencast from 2025-05-02 15-08-42.webm](https://github.com/user-attachments/assets/d7423314-9eab-4335-9503-60bec66ceb65)

feat(layer selection): new ui for layer and file selection

---

docs/usage/processings.md
geoplateforme/gui/upload_creation/qwp_upload_creation.py
geoplateforme/processing/upload_database_integration.py
geoplateforme/processing/upload_from_layers.py
geoplateforme/processing/vector_db_creation.py
geoplateforme/resources/help/vector_db_creation.md

- Modification processing de création de base de données vectorielle depuis des couches pour ne plus prendre en paramètre un fichier .json mais des paramètres de processing.
- ajout prise en compte couches QGIS en entrée
- utilisation des couches définies par l'utilisateur
- ajout des tags sur l'upload lors de la création de la base de données vectorielle
- ajout documentation
TODO :

feat(vector db creation): use layers for vector db creation

---

geoplateforme/gui/dashboard/dlg_stored_data_details.py
geoplateforme/gui/mdl_stored_data.py
geoplateforme/gui/tile_creation/qwp_tile_generation_edition.py
geoplateforme/gui/tile_creation/wzd_tile_creation.py

- ajout d'une `QToolBar` dans `StoredDataDetailsDialog` pour l'affichage des actions disponibles en fonction de la donnée affichée
- Pour les `VECTOR-DB`:
- ajout action pour génération de tuiles vectorielles
- Modification du wizard de génération de tuiles vectorielles `TileCreationWizard` pour la prise en compte de dataset et stored_data_id dans le constructeur
- si les paramètres sont définis, la combobox associée est désactivée
- fix selection d'une stored data dans le combobox. Il faut utiliser la stored data stocké dans UserRole pour pouvoir récupérer l'ID

feat(tile generation): add action for tile generation in vector db stored data details

---

geoplateforme/gui/dashboard/dlg_stored_data_details.py
geoplateforme/gui/publication_creation/qwp_publication_form.py
geoplateforme/gui/publication_creation/wzd_publication_creation.py

- ajout d'action pour les PYRAMID-VECTOR:
- ajout action pour publication de tuiles vectorielles
- Modification du wizard de publication de tuiles vectorielles `PublicationFormCreation` pour la prise en compte de dataset et stored_data_id dans le constructeur
- si les paramètres sont définis, la combobox associée est désactivée

feat(tile publish): add action for tile publication in pyramid vector stored data details

---

geoplateforme/api/configuration.py
geoplateforme/api/custom_exceptions.py
geoplateforme/api/stored_data.py
geoplateforme/gui/dashboard/wdg_dashboard.py
geoplateforme/gui/dashboard/wdg_dashboard.ui
geoplateforme/gui/mdl_configuration.py
geoplateforme/gui/publication_creation/wdg_publication_form.py
geoplateforme/processing/delete_data.py
geoplateforme/processing/unpublish.py
geoplateforme/processing/upload_publication.py

- ajout de fonctions pour récupérer l'ensemble des configurations (services) disponibles pour un dataset
- ajout d'un model pour affichage des configurations sous forme de tableau
- affichage du tableau dans le dashboard
- suppression utilisation du tags `tms_url` dans les données stockées. La limite de 99 caractères est souvent atteinte. Le tag n'est plus utilisé dans la géoplateforme.
🎫 JIRA :
- https://jira.worldline-solutions.com/browse/IGNGPF-4831

feat(service): display available service in table

---

geoplateforme/constants.py
geoplateforme/metadata.txt
geoplateforme/plugin_main.py

Ajout de French Locator Filter et du plugin isoservice / itinéraire en tant que dépendance du plugin géoplateforme.
Lors de l'installation du plugin, QGIS va demander à l'utilisateur si les plugins doivent être installés:
QGIS fera automatiquement l'installation.
Le plugin va ensuite à son démarrage vérifier si des actions doivent être ajoutées dans son menu.
On vérifie si la méthode `create_gpf_plugins_actions` est présente dans le plugin externe et les actions crées sont ajoutées au menu.
Voici un example avec le plugin isoservice / itinéraire (branche non mergée pour l'instant) :

feat(external plugins): add dependencies and load actions in Geoplateforme plugin

---

geoplateforme/api/metadata.py
geoplateforme/gui/dashboard/wdg_dashboard.py
geoplateforme/toolbelt/network_manager.py

- needed on windows to avoid lock on temp file
- QgsFileDownloader can't download to a locked file
closes #56

fix(metadata): use temporary file name only but not with context

---

geoplateforme/toolbelt/network_manager.py

related #63 
Lorsqu'une erreur est remontée par l'entrepot un log est automatiquement effectué avec un affichage dans la message bar de QGIS.
Ceci pose problème lorsque la requete n'est pas lancé depuis le thread principal. On observe un crash de QGIS sous Windows.
Les logs d'erreur ne sont plus affichés dans la message bar mais uniquement dans les logs du plugin.
Concernant le lancement des processings dans les wizard. Les logs sont affichés en cas d'erreur.

fix(network manager): don't push log in message bar to avoid crashes in Windows

---

geoplateforme/processing/upload_from_layers.py

closes #66 
Les fichiers GPKG peuvent contenir plusieurs couches et lorsque l'on sélectionne une couche QGIS provenant d'un GPKG comme le fichier est utiliser, TOUTES les couches sont importées.
Afin d'éviter ce problème, lorsqu'une couche provient d'un GPKG un export de la couche unique est effectué dans un GPKG temporaire.

fix(upload): always use temporary file for gpkg layers to avoid upload of other layers

---

geoplateforme/gui/tile_creation/qwp_tile_generation_status.py
geoplateforme/processing/tile_creation.py
geoplateforme/resources/help/tile_creation.md

Ajout d'une option dans le processing de génération de tuiles vectorielles pour attendre la fin de la génération.
Récupération de la données stockées créee juste après le lancement du processing.

feat(tile): wait option in tile generation processing

---

geoplateforme/api/upload.py
geoplateforme/processing/upload_from_files.py

Regression suite à la modification du `NetworkManager` pour l'envoi de fichier de style. On doit obligatoirement passer par des `Path`.

fix(upload): add_file need a Path and not a str

---

geoplateforme/api/datastore.py

Si plusieurs endpoint sont disponibles pour un type de publication il faut bien prendre le endpoint open pour les publications.

fix(endpoint): add option to use open endpoint

---

geoplateforme/gui/dashboard/wdg_service_details.py
geoplateforme/gui/dashboard/wdg_service_details.ui
geoplateforme/gui/permissions/mdl_permissions.py
geoplateforme/gui/permissions/wdg_permissions.py
geoplateforme/gui/permissions/wdg_permissions.ui

- Affichage des permissions sur les services fermés
- création d'un modèle pour affichage des permissions sous forme de table
- création d'un widget pour affichage des permissions
- ajout du widget dans l'affichage des services si le service est fermé
🎫 JIRA :
- https://jira.worldline-solutions.com/browse/IGNGPF-4866

feat(permission): add widget to display permission in closed services

---

geoplateforme/api/catalogs.py
geoplateforme/api/custom_exceptions.py
geoplateforme/api/user.py
geoplateforme/gui/mdl_community.py

Ajout des communautés publiques pour la création d'une permission.
- Récupération des communautés publique depuis `/catalogs/communities`
- Ajout des communautés dans le modèle

feat(permission): display public community for creation

---

geoplateforme/api/offerings.py
geoplateforme/gui/dashboard/wdg_service_details.py
geoplateforme/gui/dashboard/wdg_service_details.ui
geoplateforme/gui/styles/dlg_configuration_style_creation.py
geoplateforme/gui/styles/dlg_configuration_style_creation.ui
geoplateforme/gui/styles/wdg_configuration_style.py
geoplateforme/gui/styles/wdg_configuration_style.ui
geoplateforme/gui/styles/wdg_mapbox_style_creation.py
geoplateforme/gui/styles/wdg_mapbox_style_creation.ui
geoplateforme/gui/styles/wdg_sld_selection.py
geoplateforme/gui/styles/wdg_sld_selection.ui
geoplateforme/gui/styles/wdg_wfs_style_creation.py
geoplateforme/gui/styles/wdg_wfs_style_creation.ui
geoplateforme/processing/provider.py
geoplateforme/processing/style/delete_configuration_style.py
geoplateforme/resources/help/delete_configuration_style.md

- ajout d'un processing pour supprimer un style d'une configuration depuis son nom : `DeleteConfigurationStyleAlgorithm` / `delete_configuration_style`
- ajout d'un composant pour l'affichage des styles d'une configuration : `ConfigurationStylesWidget`
- utilisation du processing pour création d'un style dans une configuration `AddConfigurationStyleAlgorithm` / `add_configuration_style`
- definition du style pour la configuration avec une dialog dédiée qui définit le style selon le type de couche
- pour WFS : sélection d'un sld pour chaque layer
- pour les autres : sélection d'un fichier mapbox au format .json
Screenshots

feat(style): display configuration style for a service

---

geoplateforme/gui/dashboard/dlg_stored_data_details.py
geoplateforme/gui/dashboard/dlg_stored_data_details.ui
geoplateforme/gui/dashboard/wdg_service_details.py
geoplateforme/gui/dashboard/wdg_service_details.ui
geoplateforme/gui/dashboard/wdg_upload_details.py
geoplateforme/gui/dashboard/wdg_upload_details.ui

Les actions disponibles ne sont pas toujours visibles car on utilise une QToolbar qui va afficher une fleche pour indiquer que des actions complémentaires sont disponibles :
L'utilisation de la tollbar est supprimée et les actions sont maintenant ajoutées dans un layout classique:
related #110

fix(actions): use layout instead of toolbar for actions

---

geoplateforme/gui/styles/wdg_sld_selection.py
geoplateforme/gui/styles/wdg_sld_selection.ui
geoplateforme/gui/wfs_publication/qwp_wfs_publication_status.py
geoplateforme/gui/wms_vector_publication/wdg_table_style_selection.py
geoplateforme/gui/wms_vector_publication/wdg_table_style_selection.ui
geoplateforme/processing/tools/sld11-10.xsl
geoplateforme/processing/tools/sld_downgrade.py

related #112 
- Ajout d'une option pour la création d'un fichier .sld 1.0.0 depuis la sélection d'une couche vectorielle
Lors de la publication d'un WMS-Vecteur:
Lors de l'ajout d'un style pour WFS:
- Suppression balise se:Description and se:Rule lors du downgrade 1.0.0 (permet d'utiliser des styles catégorisés)
- Correction texte affiché pour statut publication WFS

feat(sld): add option to create sld file from layer

---

geoplateforme/api/offerings.py
geoplateforme/gui/publication/qwp_visibility.py
geoplateforme/gui/publication/qwp_visibility.ui
geoplateforme/gui/publication_creation/qwp_status.py
geoplateforme/gui/publication_creation/wzd_publication_creation.py
geoplateforme/gui/qwp_metadata_form.py
geoplateforme/gui/wfs_publication/qwp_wfs_publication_status.py
geoplateforme/gui/wfs_publication/wzd_publication_creation.py
geoplateforme/gui/wms_raster_publication/qwp_wms_raster_publication_status.py
geoplateforme/gui/wms_raster_publication/wzd_publication_creation.py
geoplateforme/gui/wms_vector_publication/qwp_wms_vector_publication_status.py
geoplateforme/gui/wms_vector_publication/wzd_publication_creation.py
geoplateforme/gui/wmts_publication/qwp_wmts_publication_status.py
geoplateforme/gui/wmts_publication/wzd_publication_creation.py
geoplateforme/processing/publication/upload_publication.py
geoplateforme/processing/publication/wfs_publication.py
geoplateforme/processing/publication/wms_publication.py
geoplateforme/processing/publication/wms_raster_publication.py
geoplateforme/processing/publication/wmts_publication.py
geoplateforme/resources/help/vector_tile_publish.md
geoplateforme/resources/help/wfs_publish.md
geoplateforme/resources/help/wms_publish.md
geoplateforme/resources/help/wms_raster_publish.md
geoplateforme/resources/help/wmts_publish.md

- Mise à jour création offering pour définir la visibilité via le paramètre `open`
- suppression utilisation paramètre `visibility`
- Mise à jour des processing de publication pour définir la visibilité:
- Récupération du endpoint privé
- Définition de la visibilité de l'offering
- Ajout d'une page wizard pour définir la visibilité des publications

feat(publish): add page to define publication visibility

---

geoplateforme/gui/provider/capabilities_reader.py
geoplateforme/gui/provider/provider_dialog.py

La configuration d'authentification n'était pas utilisée pour le chargement des couches privées.

fix(provider): use user define authid for authentication

---

geoplateforme/gui/wfs_publication/wdg_table_relation.py

related #210 
Des erreurs peuvent survenir à la publication ou lors du chargement des couches si le nom public d'une couche contient des caractères spéciaux:
- espace : impossible de charger la couche dans QGIS
- `+` : erreur lors de la publication
On ajoute un validateur pour le nom public pour éviter ces erreurs.

feat(wfs): add validator for public name

---

geoplateforme/gui/styles/wdg_sld_selection.py

related #112 
Désactivation des vérifications des .sld en entrée / sortie pour éviter des appels web sans le proxy défini dans QGIS ou via le système (nécessaire pour la récupération des schémas à vérifier)

feat(sld from layer): disable checks to avoid error if proxy needed for schema download

---

geoplateforme/toolbelt/preferences.py

related #233
La configuration du plugin n'était pas OK car il y avait un espace en trop dans la définition de l'identifiant du processing de génération de base vectorielle.
Afin de minimiser ce risque d'erreur on enlève les espaces lors de la lecture des identifiants.

fix(processing): be more robust for processing search from id

---

geoplateforme/gui/dashboard/dlg_stored_data_details.py
geoplateforme/gui/dashboard/wdg_upload_details.py

related #229 
Les logs de génération étaient toujours dupliqués. On supprime maintenant les logs existant avant la mise à jour.

fix(report): avoid duplicate of generation report

---

docs/usage/processings.md
geoplateforme/processing/utils.py

Le lien vers la documentation depuis les processings allaient bien vers la page sur les traitements mais pas directement sur le processing en cours d'utilisation.
Les références avec des `_` ne sont pas supportés (en tout ca j'ai pas réussi à les faire fonctionner. En mettant `-` cela fonctionne.

fix(doc): invalid links for processings

---

geoplateforme/gui/wfs_publication/qwp_table_relation.ui

- needed to avoid use of space when collapsed
related #242

feat(wfs): use QScrollArea to use collapsible group box

---

geoplateforme/api/metadata.py
geoplateforme/api/offerings.py
geoplateforme/gui/mdl_offering.py
geoplateforme/gui/permissions/wdg_permission.py
geoplateforme/gui/permissions/wdg_permission_creation.py

Il y avait beaucoup de requête pour récupérer les offres d'un entrepot sans filtre sur le dataset. 
On faisait 2 requêtes pour chaque configuration. 
On utilise maintenant la route `/datastore/{datastore]/offerings` pour récupérer les offres.
Il y avait aussi des requêtes non nécessaire pour les champs de type bool.
Le modele de visualisation des offres peut maintenant directement ne récupérer que les offres ouvertes ou fermées sans passer par un proxy modele.

fix(offering model): use /datastore/{datastore]/offerings to get list of offering if no dataset defined

---

geoplateforme/plugin_main.py

Ajout d'un séparateur pour distinguer les actions des plugins externes.

feat(menu): add separator before external plugin actions

---

geoplateforme/api/metadata.py
geoplateforme/gui/dashboard/wdg_service_details.py
geoplateforme/toolbelt/dlg_processing_run.py
geoplateforme/toolbelt/dlg_processing_run.ui
geoplateforme/toolbelt/text_edit_feedback.py

Pendant la dépublication il est nécessaire de faire une mise à jour des métadonnées.
Pendant le traitement la fenetre de QGIS freeze et on a l'impression que QGIS peut avoir planter.
Le lancement du processing de dépublication est effectué dans une QDialog qui va attendre le résultat du processing et affiché une erreur en cas de problème.
Correction d'un bug sur la dépublication, un exception était lancée lors de la lecture des métadonnées.

Fix/no UI freeze during unpublish

---

geoplateforme/gui/dashboard/wdg_dashboard.py
geoplateforme/gui/permissions/wdg_permissions.py

Modification de l'UI pour que les tables respectent l'espace disponible :

fix(dashboard): fix column size in dashboard tables

---

geoplateforme/gui/dashboard/dlg_stored_data_details.py
geoplateforme/gui/dashboard/wdg_dashboard.py
geoplateforme/processing/tools/delete_offering.py
geoplateforme/processing/tools/delete_stored_data.py
geoplateforme/resources/help/delete_offering.md

related #313 
Lors de la demande de suppression d'un jeu de données, l'interface graphique ne freeze plus car on lance les processing de suppression des données associées dans un tache.
L'utilisateur ne peut pas effectuer d'action pendant le traitement.
Mise en place du même mécanisme pour la suppression des données stockées.
Le processing de suppression des offres est mis à jour pour pouvoir supprimer plusieurs offres en même temps.
Ceci permet de n'effectuer la mise à jour de la métadata une seule fois après la suppression de l'offre.
Le processing de suppression des données stockées appelle maintenant le processing de suppression des offres pour que les styles soient supprimées et la métadata mise à jour. related #290

Feat/no UI freeze for dataset delete

---

geoplateforme/gui/dashboard/dlg_stored_data_details.py
geoplateforme/gui/publication_creation/qwp_publication_form.py
geoplateforme/gui/publication_creation/qwp_publication_form.ui
geoplateforme/gui/publication_creation/wzd_publication_creation.py
geoplateforme/gui/wfs_publication/qwp_table_relation.py
geoplateforme/gui/wfs_publication/qwp_table_relation.ui
geoplateforme/gui/wfs_publication/wzd_publication_creation.py
geoplateforme/gui/wms_vector_publication/qwp_table_style_selection.py
geoplateforme/gui/wms_vector_publication/qwp_table_style_selection.ui
geoplateforme/gui/wms_vector_publication/wzd_publication_creation.py

Dans les fenetres de publication des requetes vers la géoplateforme était systématiquement effectuées pour pouvoir remplir des combobox qui ne pouvaient pas être modifiées par l'utilisateur.
On passe maintenant directement les informations nécessaire à la publication sans afficher les combobox.

feat(optim): avoid data load for publication
